export const TYPE = {
    EDIT_LIST: "EDIT_LIST",
    EDIT_VISIBLE_UN_CHECK_BOTTOMSHEET: "EDIT_VISIBLE_UN_CHECK_BOTTOMSHEET" ,
    EDIT_VISIBLE_CHECK_BOTTOMSHEET: "EDIT_VISIBLE_CHECK_BOTTOMSHEET",
    EDIT_FLEXT_TEXTINPUT_COLOR: "EDIT_FLEXT_TEXTINPUT_COLOR",
    EDIT_FLEXT_TEXTINPUT: "EDIT_FLEXT_TEXTINPUT",
}